/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ModeratorRouteImport } from './routes/moderator'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeratorIndexRouteImport } from './routes/moderator.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ModeratorReportsRouteImport } from './routes/moderator.reports'
import { Route as ModeratorListingsRouteImport } from './routes/moderator.listings'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardListingsRouteImport } from './routes/dashboard.listings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorRoute = ModeratorRouteImport.update({
  id: '/moderator',
  path: '/moderator',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorIndexRoute = ModeratorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeratorRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ModeratorReportsRoute = ModeratorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorListingsRoute = ModeratorListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => ModeratorRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingsRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingsRoute = DashboardListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/moderator': typeof ModeratorRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/moderator/listings': typeof ModeratorListingsRoute
  '/moderator/reports': typeof ModeratorReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/moderator/': typeof ModeratorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/moderator/listings': typeof ModeratorListingsRoute
  '/moderator/reports': typeof ModeratorReportsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/moderator': typeof ModeratorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/moderator': typeof ModeratorRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/moderator/listings': typeof ModeratorListingsRoute
  '/moderator/reports': typeof ModeratorReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/moderator/': typeof ModeratorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/listings'
    | '/login'
    | '/messages'
    | '/moderator'
    | '/notifications'
    | '/register'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/listings'
    | '/admin/reports'
    | '/admin/users'
    | '/dashboard/listings'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/listings/$id'
    | '/moderator/listings'
    | '/moderator/reports'
    | '/admin/'
    | '/dashboard/'
    | '/moderator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/listings'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/register'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/listings'
    | '/admin/reports'
    | '/admin/users'
    | '/dashboard/listings'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/listings/$id'
    | '/moderator/listings'
    | '/moderator/reports'
    | '/admin'
    | '/dashboard'
    | '/moderator'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/listings'
    | '/login'
    | '/messages'
    | '/moderator'
    | '/notifications'
    | '/register'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/listings'
    | '/admin/reports'
    | '/admin/users'
    | '/dashboard/listings'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/listings/$id'
    | '/moderator/listings'
    | '/moderator/reports'
    | '/admin/'
    | '/dashboard/'
    | '/moderator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ModeratorRoute: typeof ModeratorRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator': {
      id: '/moderator'
      path: '/moderator'
      fullPath: '/moderator'
      preLoaderRoute: typeof ModeratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/': {
      id: '/moderator/'
      path: '/'
      fullPath: '/moderator/'
      preLoaderRoute: typeof ModeratorIndexRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/moderator/reports': {
      id: '/moderator/reports'
      path: '/reports'
      fullPath: '/moderator/reports'
      preLoaderRoute: typeof ModeratorReportsRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/moderator/listings': {
      id: '/moderator/listings'
      path: '/listings'
      fullPath: '/moderator/listings'
      preLoaderRoute: typeof ModeratorListingsRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings': {
      id: '/dashboard/listings'
      path: '/listings'
      fullPath: '/dashboard/listings'
      preLoaderRoute: typeof DashboardListingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardListingsRoute: typeof DashboardListingsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardListingsRoute: DashboardListingsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ListingsRouteChildren {
  ListingsIdRoute: typeof ListingsIdRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsIdRoute: ListingsIdRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface ModeratorRouteChildren {
  ModeratorListingsRoute: typeof ModeratorListingsRoute
  ModeratorReportsRoute: typeof ModeratorReportsRoute
  ModeratorIndexRoute: typeof ModeratorIndexRoute
}

const ModeratorRouteChildren: ModeratorRouteChildren = {
  ModeratorListingsRoute: ModeratorListingsRoute,
  ModeratorReportsRoute: ModeratorReportsRoute,
  ModeratorIndexRoute: ModeratorIndexRoute,
}

const ModeratorRouteWithChildren = ModeratorRoute._addFileChildren(
  ModeratorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  ListingsRoute: ListingsRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ModeratorRoute: ModeratorRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
